
export const CURRENT_USER_ON_CHANGE = 'CURRENT_USER_ON_CHANGE';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const CURRENT_USER_EXTEND = 'CURRENT_USER_EXTEND'
export const LOADING_PAGE = "LOADING_PAGE"
export const LOADED_PAGE = "LOADED_PAGE"