export const ListProductMockup = [
  {
    id: 1,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 3,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 2,
    image: '/assets/image/laptop2.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 3,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 4,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 4,
    image: '/assets/image/laptop2.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 1,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 5,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 2,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 6,
    image: '/assets/image/laptop2.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 0,
    reviews: 1,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 7,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 8,
    image: '/assets/image/laptop2.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 9,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 10,
    image: '/assets/image/laptop2.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
  {
    id: 11,
    image: '/assets/image/laptop1.png',
    title: 'EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...',
    price: 100000,
    priceDiscount: 200000,
    inStock: 2,
    reviews: 5,   
    quantity: 0,
    brand : "MSI",
  },
];
